adfinis/timed

- backend/timed/notifications/templates/budget_reminder.txt
> chore: update budget reminder text

- frontend/mirage/config.js
- frontend/mirage/factories/absence-balance.js
- frontend/mirage/factories/absence-credit.js
- frontend/mirage/factories/absence-type.js
- frontend/mirage/factories/absence.js
- frontend/mirage/factories/activity.js
- frontend/mirage/factories/attendance.js
- frontend/mirage/factories/billing-type.js
- frontend/mirage/factories/cost-center.js
- frontend/mirage/factories/customer-statistic.js
- frontend/mirage/factories/customer.js
- frontend/mirage/factories/employment.js
- frontend/mirage/factories/location.js
- frontend/mirage/factories/month-statistic.js
- frontend/mirage/factories/overtime-credit.js
- frontend/mirage/factories/project-assignee.js
- frontend/mirage/factories/project-statistic.js
- frontend/mirage/factories/project.js
- frontend/mirage/factories/public-holiday.js
- frontend/mirage/factories/report-intersection.js
- frontend/mirage/factories/report.js
- frontend/mirage/factories/task-statistic.js
- frontend/mirage/factories/task.js
- frontend/mirage/factories/user-statistic.js
- frontend/mirage/factories/user.js
- frontend/mirage/factories/worktime-balance.js
- frontend/mirage/factories/year-statistic.js
- frontend/mirage/serializers/application.js
- frontend/package.json
- frontend/pnpm-lock.yaml
this should allow us to get to ember-data v4.8
> chore(frontend): use ember-cli-mirage v3

- frontend/package.json
- frontend/pnpm-lock.yaml
Upgrade to [v15.0.0](https://github.com/shepherd-pro/ember-shepherd/releases/tag/v15.0.0)
Tested locally - works.
> chore(deps): upgrade ember-shepherd

- frontend/app/index/controller.js
> fix(frontend): only show public-holidays of users location

- backend/timed/projects/admin.py
fixes: https://github.com/adfinis/timed/issues/228
> fix(backend): projects can't be created in django-admin

- frontend/app/abilities/report.js
> fix(frontend/abilities/report]): dont access users id without .get

- frontend/app/index/reports/route.js
> fix(frontend/magic-link): include project && customer when fetching task

- backend/timed/employment/views.py
> fix(backend/credits): don't return the same credit multiple times

- frontend/app/index/template.hbs
> fix(frontend): adjust naming

- frontend/app/components/magic-link-btn/template.hbs
> fix(frontend/magic-link): button is now round again when modal is opened

- frontend/Dockerfile
get these https://github.com/adfinis/timed/security/code-scanning down to 0
> fix(frontend): update deps in container image

- backend/timed/tracking/tasks.py
> feat(backend/mails): set reply-to header to reviewers email

- frontend/app/projects/controller.js
- frontend/app/projects/template.hbs
> feat(frontend/projects): added checkbox for hiding archived tasks

- frontend/app/models/absence-balance.js
- frontend/app/models/absence-credit.js
- frontend/app/models/absence.js
- frontend/app/models/activity.js
- frontend/app/models/project.js
- frontend/app/models/report.js
- frontend/app/models/user.js
applied `git diff upstream/main frontend/app/models` from #436
> chore(frontend/models): adjust for ember-data v5.3

- frontend/app/components/statistic-list/template.hbs
- frontend/app/users/index/template.hbs
> chore(frontend): fix ember data deprecate array like

- frontend/app/components/sy-durationpicker-day/component.js
- frontend/app/utils/parse-daytime.js
- frontend/tests/unit/utils/parse-daytime-test.js
- frontend/tests/unit/utils/parse-filename-test.js
> feat(frontend/durationpicker-day): auto format time

- frontend/app/components/checkmark.hbs
> fix(frontend): checkmark hidden with certain backgrounds

- frontend/app/components/checkbox.hbs
> fix(frontend/checkbox): adjust label font size to match other form elements

- frontend/app/components/weekly-overview-day.hbs
> fix(frontend): holidays marked as regular wordays

- frontend/app/styles/components/power-calendar.css
> fix(frontend/calendar): highlight today && highlight hovered days in light mode

- frontend/app/abilities/report.js
- frontend/app/analysis/index/controller.js
- frontend/app/analysis/index/template.hbs
- frontend/app/app.js
- frontend/app/components/can-edit.hbs
- frontend/app/components/report-row.hbs
- frontend/app/components/report-row.js
- frontend/package.json
- frontend/pnpm-lock.yaml
- frontend/tests/integration/components/report-row/component-test.js
- frontend/tests/unit/abilities/report-test.js
> refactor(frontend): async report ability

- backend/poetry.lock
- backend/pyproject.toml
see https://github.com/django-hurricane/django-hurricane/issues/140
> fix(backend): pin tornado
